version: '3.8'

services:
  celery-worker:
    build: .
    volumes:
      - .:/app
    command: ["celery", "-A", "backend.worker.celery", "worker", "--loglevel=info"]
    depends_on:
      - postgres-jam-db
      - rabbitmq-jam
    environment:
      CELERY_BROKER_URL: amqp://rabbitmq:rabbitmq@rabbitmq-jam//
      DATABASE_URL: postgresql://postgres:postgres@postgres-jam-db:5432/harmonicjam

  postgres-jam-db:
    image: postgres:15.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harmonicjam
      POSTGRES_HOST_AUTH_METHOD: trust
      PG_LOG_MIN_MESSAGES: warning
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    
  rabbitmq-jam:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  web-api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
      - 5678:5678 
    command: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - postgres-jam-db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-jam-db:5432/harmonicjam

volumes:
  postgres_data:
  rabbitmq_data:
